version : '3.8'

services:
  finance_app:
    image: image_finapp:1
    container_name: finance_app
    depends_on:
      - finance_db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://finance_db:3306/db_paymybuddy
      SPRING_DATASOURCE_USERNAME:  ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

  finance_db:
    image: mysql:8.0
    container_name: finance_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/
    
volumes:
  mysql_data:
