version : '3.8'

services:
  finance_app:
    image: image_finapp:1
    container_name: finance_app
    depends_on:
      - finance_db
    ports:
      - "8080:8080"
    env_file:
     - .env1
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://finance_db:3306/db_paymybuddy
       
  finance_db:
    image: mysql:8.0
    container_name: finance_db
    env_file:
     - .env2
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb/create.sql:/docker-entrypoint-initdb.d/create.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  mysql_data:
